#!/usr/bin/env bash

app_home="$(dirname ${BASH_SOURCE})"
app_name="$(basename ${BASH_SOURCE})"
app_version=0.0.1

function main {
  if [[ $# -eq 0 ]]; then
    ${app_home}/cmd/help.sh "${app_name}" "${app_version}"
    exit 1
  fi

  command_name=$1
  shift
  case $command_name in

    help|--help|-h)
      ${app_home}/cmd/help.sh "${app_name}" "${app_version}" "$@"
      exit 1
    ;;

    apps*)
      ${app_home}/cmd/apps/main.sh "${app_name}" "${app_version}" $command_name "$@"
      exit 0
    ;;

    start)
      ${app_home}/cmd/apps/main.sh "${app_name}" "${app_version}" apps:start "$@"
      exit 0
    ;;

    stop)
      ${app_home}/cmd/apps/main.sh "${app_name}" "${app_version}" apps:stop "$@"
      exit 0
    ;;

    version|--version|-v)
      ${app_home}/cmd/version.sh "${app_name}" "${app_version}"
      exit 1
    ;;

    *)
      ${app_home}/cmd/help.sh "${app_name}" "${app_version}" $command_name
      exit 1
    ;;
  esac
}

main "$@"
